name: Events - Activity Types and Filters
on: 
  pull_request:
    types: [opened, edited]
    branches:
      - main
      - 'feat/**' # feat/new feat/new/cat
      - 'dev-*' # dev-new
    
  workflow_dispatch:
  push:
    branches:
      - main
      - 'feat/**' # feat/new feat/new/cat
      - 'dev-*' # dev-new
      # developer-1 would not trigger this workflow
    paths-ignore:
      - '.github/workflows'
      - '**/README.md'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Output event data
        run: echo "${{ toJSON(github.event) }}"
      - name: Get code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Test code
        run: npm run test
      - name: Build code
        run: npm run build
      - name: Deploy project
        run: echo "Deploying..."